"""initial schema

Revision ID: b09f3c9ff3b0
Revises: 
Create Date: 2026-10-01 15:27:27.170098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09f3c9ff3b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('build_hash', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('input_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_org_id'), ['org_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)

    op.create_table('clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('existing_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_clients_org_slug')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_org_id'), ['org_id'], unique=False)

    op.create_table('orgs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('required_approvals', sa.JSON(), nullable=False),
    sa.Column('default_jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('llm_budget_micros', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_runs',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('output_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_org_id'), ['org_id'], unique=False)

    op.create_table('approvals',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_org_id'), ['org_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('client_facts',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_facts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_facts_org_id'), ['org_id'], unique=False)

    op.create_table('client_llm_budgets',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('budget_micros', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'client_id', name='uq_client_llm_budget')
    )
    with op.batch_alter_table('client_llm_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_llm_budgets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_llm_budgets_org_id'), ['org_id'], unique=False)

    op.create_table('conversations',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_ref', sa.String(length=64), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_visitor_ref'), ['visitor_ref'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_org_id'), ['org_id'], unique=False)

    op.create_table('sites',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('design_preset_id', sa.String(length=100), nullable=False),
    sa.Column('current_build_hash', sa.String(length=128), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_org_id'), ['org_id'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content_redacted', sa.Text(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_org_id'), ['org_id'], unique=False)

    op.create_table('lead_submissions',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spam_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('utm_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_submissions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_submissions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_submissions_site_id'), ['site_id'], unique=False)

    op.create_table('llm_invocations',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_invocations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_invocations_org_id'), ['org_id'], unique=False)

    op.create_table('research_runs',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('query_plan_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_org_id'), ['org_id'], unique=False)

    op.create_table('site_versions',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('build_hash', sa.String(length=128), nullable=False),
    sa.Column('content_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('content_schema_version', sa.String(length=32), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=False),
    sa.Column('design_preset_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_hash')
    )
    with op.batch_alter_table('site_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_versions_org_id'), ['org_id'], unique=False)

    op.create_table('build_validations',
    sa.Column('site_version_id', sa.Uuid(), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['site_version_id'], ['site_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_validations_org_id'), ['org_id'], unique=False)

    op.create_table('deploys',
    sa.Column('site_version_id', sa.Uuid(), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['site_version_id'], ['site_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deploys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deploys_org_id'), ['org_id'], unique=False)

    op.create_table('lead_events',
    sa.Column('lead_submission_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lead_submission_id'], ['lead_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_events_lead_submission_id'), ['lead_submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_events_org_id'), ['org_id'], unique=False)

    op.create_table('research_sources',
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sources_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sources_research_run_id'), ['research_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_sources_org_id'))

    op.drop_table('research_sources')
    with op.batch_alter_table('lead_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_lead_events_lead_submission_id'))

    op.drop_table('lead_events')
    with op.batch_alter_table('deploys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deploys_org_id'))

    op.drop_table('deploys')
    with op.batch_alter_table('build_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_validations_org_id'))

    op.drop_table('build_validations')
    with op.batch_alter_table('site_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_versions_org_id'))

    op.drop_table('site_versions')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_research_runs_client_id'))

    op.drop_table('research_runs')
    with op.batch_alter_table('llm_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_invocations_org_id'))
        batch_op.drop_index(batch_op.f('ix_llm_invocations_client_id'))

    op.drop_table('llm_invocations')
    with op.batch_alter_table('lead_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_submissions_site_id'))
        batch_op.drop_index(batch_op.f('ix_lead_submissions_org_id'))
        batch_op.drop_index(batch_op.f('ix_lead_submissions_client_id'))

    op.drop_table('lead_submissions')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_org_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_org_id'))

    op.drop_table('sites')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_client_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_visitor_ref'))
        batch_op.drop_index(batch_op.f('ix_conversations_org_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_client_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('client_llm_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_llm_budgets_org_id'))
        batch_op.drop_index(batch_op.f('ix_client_llm_budgets_client_id'))

    op.drop_table('client_llm_budgets')
    with op.batch_alter_table('client_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_facts_org_id'))
        batch_op.drop_index(batch_op.f('ix_client_facts_client_id'))

    op.drop_table('client_facts')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_org_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_client_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('orgs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_org_id'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_org_id'))

    op.drop_table('artifacts')
    # ### end Alembic commands ###
